void main ( ) {
    x [ x ] ;
    x [ x ] = x [ x ] ;
    x . x ;
    x . x = x . x ;
    x - x ;
    x - x = x - x ;
    x * x ;
    x * x = x * x ;
    x > x ;
    x > x = x > x ;
    x < x ;
    x < x = x < x ;
    x >= x ;
    x >= x = x >= x ;
    x <= x ;
    x <= x = x <= x ;
    x != x ;
    x != x = x != x ;
    x == x ;
    x == x = x == x ;
    x + x ;
    x + x = x + x ;
    x / x ;
    x / x = x / x ;
    x % x ;
    x % x = x % x ;
    x || x ;
    x || x = x || x ;
}